import scrapy

class EntidadItem(scrapy.Item):
    tipo_poder_id = scrapy.Field()
    tipo_poder_nombre = scrapy.Field()
    categoria = scrapy.Field()
    entidad_id = scrapy.Field()
    entidad_nombre = scrapy.Field()

class TipoPoderItem(scrapy.Item):
    tipo_poder_id = scrapy.Field()
    tipo_poder_nombre = scrapy.Field()

class ViaticoPasajeItem(scrapy.Item):
    tipo_poder_id = scrapy.Field()
    tipo_poder_nombre = scrapy.Field()
    categoria = scrapy.Field()
    entidad_id = scrapy.Field()
    entidad_nombre = scrapy.Field()
    codmes = scrapy.Field()
    pk_viaticos = scrapy.Field()
    fk_fue_financiamiento = scrapy.Field()
    fuente = scrapy.Field()
    vc_ruc_entidad = scrapy.Field()
    ch_viaticos_tipo = scrapy.Field()
    ch_viaticos_ruta = scrapy.Field()
    vc_viaticos_anno = scrapy.Field()
    vc_viaticos_mes = scrapy.Field()
    vc_viaticos_area = scrapy.Field()
    vc_viaticos_usuarios = scrapy.Field()
    dt_viaticos_fechas = scrapy.Field()
    dt_viaticos_fechas_retorno = scrapy.Field()
    vc_viaticos_ruta = scrapy.Field()
    vc_viaticos_autorizacion = scrapy.Field()
    dc_viaticos_costo_pasajes_n = scrapy.Field()
    dc_viaticos_via_n = scrapy.Field()
    dc_viaticos_total_n = scrapy.Field()
    dc_viaticos_costo_pasajes_e = scrapy.Field()
    dc_viaticos_via_e = scrapy.Field()
    dc_viaticos_total_e = scrapy.Field()
    vc_viaticos_resolucion = scrapy.Field()

class OrdenServicioItem(scrapy.Item):
    tipo_poder_id = scrapy.Field()
    tipo_poder_nombre = scrapy.Field()
    categoria = scrapy.Field()
    entidad_id = scrapy.Field()
    entidad_nombre = scrapy.Field()
    codmes = scrapy.Field()    
    pk_id_orden = scrapy.Field()
    fk_id_orden_tipo = scrapy.Field()
    vc_orden_ruc = scrapy.Field()
    vc_orden_periodo = scrapy.Field()
    vc_orden_numero = scrapy.Field()
    vc_orden_numero_siaf = scrapy.Field()
    dt_orden_fecha = scrapy.Field()
    dc_orden_monto = scrapy.Field()
    vc_orden_proveedor = scrapy.Field()
    vc_orden_descripcion = scrapy.Field()
    dt_orden_fec_reg = scrapy.Field()
    in_orden_anno = scrapy.Field()
    in_orden_mes = scrapy.Field()

class PersonaItem(scrapy.Item):
    tipo_poder_id = scrapy.Field()
    tipo_poder_nombre = scrapy.Field()
    categoria = scrapy.Field()
    entidad_id = scrapy.Field()
    entidad_nombre = scrapy.Field()
    codmes = scrapy.Field()
    pk_id_personal = scrapy.Field()
    vc_personal_ruc_entidad = scrapy.Field()
    in_personal_anno = scrapy.Field()
    in_personal_mes = scrapy.Field()
    vc_personal_regimen_laboral = scrapy.Field()
    vc_personal_paterno = scrapy.Field()
    vc_personal_materno = scrapy.Field()
    vc_personal_nombres = scrapy.Field()
    vc_personal_cargo = scrapy.Field()
    vc_personal_dependencia = scrapy.Field()
    mo_personal_remuneraciones = scrapy.Field()
    mo_personal_honorarios = scrapy.Field()
    mo_personal_incentivo = scrapy.Field()
    mo_personal_gratificacion = scrapy.Field()
    mo_personal_otros_beneficios = scrapy.Field()
    mo_personal_total = scrapy.Field()
    vc_personal_observaciones = scrapy.Field()
    fec_reg = scrapy.Field()
